name: 'Test Working Directory'
description: 'Test the working directory function'
inputs:
  environment:
    description: 'The env you wish to test (dev, stage, prod)'
    required: true
    default: 'dev'

runs:
  using: 'composite'
  steps:
    - name: Current Working Directory
      id: pwd
      shell: bash
      working-directory: infra/${{ inputs.environment }}
      run: echo "Current Working Directory => " && pwd

    - name: Working Directory Contents
      id: ls
      shell: bash
      working-directory: infra/${{ inputs.environment }}
      run: echo "Working Directory Contents => " && ls

    - name: Working Directory Contents
      id: hello
      shell: bash
      working-directory: infra/${{ inputs.environment }}
      run: ./hello.sh

    - name: Dig Domain
      id: dig
      shell: bash
      run: |
        IP_ADDRESS=$(dig nakama.stage.staratlas.one +short)
        echo "::set-output name=address::$IP_ADDRESS"

    - name: Print Resulits
      id: print
      shell: bash
      run: |
        echo "Your updates for Nakama [stage] have been deployed to:"
        echo "${{ steps.dig.outputs.address }}:7350"
