name: 'Test Working Directory'
description: 'Test the working directory function'

runs:
  using: 'composite'
  steps:
    - name: Current Working Directory
      id: directory
      run: echo "Current Working Directory => " && pwd

    - name: Working Directory Contents
      id: contents
      run: echo "Working Directory Contents => " && ls

    - name: Working Directory Contents
      id: hello
      run: ./hello.sh
